core:
  location: "eva_datasets"
  sqlalchemy_database_uri: 'mysql+pymysql://root:root@localhost/eva_catalog'
  application: "eva"

executor:
  batch_size: 50
storage:
  loader: "src.loaders.petastorm_loader.PetastormLoader"

server:
  host: "0.0.0.0"
  port: 5432
  socket_timeout: 60
