version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.7
    resource_class: large
    steps:
      - checkout

      - restore_cache:
          keys:
            - v5-model_cache-{{ checksum "setup.py" }}

      - restore_cache:
          keys:
            - v3-pip-cache-{{ checksum "setup.py" }}

      - restore_cache:
          keys:
            - v2-deb-cache-{{ checksum "script/antlr4/generate_parser.sh" }}

      - run:
          name: Install EVA package with test dependencies
          command: |
            python -m venv eva_dev_env
            . eva_dev_env/bin/activate
            pip install --upgrade pip
            pip install ".[dev]"

      - run:
          name: Generate Parser Files
          command: |
            sudo add-apt-repository ppa:openjdk-r/ppa
            sudo -E apt install -y openjdk-11-jdk openjdk-11-jre
            sh script/antlr4/generate_parser.sh

      - run:
          name: Test and upload coverage report to coveralls
          command: |
            . eva_dev_env/bin/activate
            sh script/test/test.sh
            coveralls

      - save_cache:
          key: v5-model_cache-{{ checksum "setup.py" }}
          paths:
            - /home/circleci/.cache/torch/hub/
            - /home/circleci/.EasyOCR/

      - save_cache:
          key: v3-pip-cache-{{ checksum "setup.py" }}
          paths:
            - ./eva_dev_env/

      - save_cache:
          key: v2-deb-cache-{{ checksum "script/antlr4/generate_parser.sh" }}
          paths:
            - /var/cache/apt/archives/


workflows:
  main:
    jobs:
      - build-and-test
