version: 2.1
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.7
      - test-3.8
      - test-3.9
      - test-3.10

jobs:
  test-3.6: &test-template
    resource_class: large
    docker:
      # https://circleci.com/docs/circleci-images#language-image-variants
      # This comes with python and openjdk11
      - image: cimg/python:3.6-browsers
    steps:
      - checkout

      - restore_cache:
          keys:
            - v9-model_cache-{{ checksum "setup.py" }}

      - restore_cache:
          keys:
            - v9-pip-cache-{{ checksum "setup.py" }}

      - run:
          name: Install EVA package with test dependencies
          command: |
            python -m venv eva_dev_env
            . eva_dev_env/bin/activate
            pip install --upgrade pip
            sh script/antlr4/generate_parser.sh
            pip install ".[dev]"

      - run:
          name: Test and upload coverage report to coveralls
          command: |
            sudo apt-get update          
            sudo apt-get install lsof 
            . eva_dev_env/bin/activate
            sh script/test/test.sh
            coveralls

      - save_cache:
          key: v9-model_cache-{{ checksum "setup.py" }}
          paths:
            - /home/circleci/.cache/torch/hub/
            - /home/circleci/.EasyOCR/

      - save_cache:
          key: v9-pip-cache-{{ checksum "setup.py" }}
          paths:
            - ./eva_dev_env/

  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7

  test-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8

  test-3.9:
    <<: *test-template
    docker:
      - image: circleci/python:3.9

  test-3.10:
    <<: *test-template
    docker:
      - image: circleci/python:3.10