version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout          

      - run:
          name: Before Install
          command: |
            sh script/install/before_install.sh
          environment:
            DEBIAN_FRONTEND: noninteractive

      - run:
          name: Install
          command: | 
            export PATH="$HOME/miniconda/bin:$PATH"
            sh script/install/install.sh

      - run:
          name: Test
          command: | 
            export PATH="$HOME/miniconda/bin:$PATH"
            conda init bash
            source ~/.bashrc
            conda activate eva
            sh script/test/test.sh
            coveralls

workflows:
  main:
    jobs:
      - build-and-test
