version: 2.1

workflows:
  main:
    jobs:
        - test:
            name: "Python v3.7"
            v: "3.7"
        - test:
            name: "Python v3.8"
            v: "3.8"

jobs:
  test: 
    parameters:
      v:
        type: string
        default: ""  # latest version
    resource_class: large
    docker:
      # https://circleci.com/docs/circleci-images#language-image-variants
      # This comes with python and openjdk11
      - image: "cimg/python:<< parameters.v >>-browsers"
    steps:
      - checkout

      - restore_cache:
          keys:
            - v10-model_cache-{{ checksum "setup.py" }}

      - restore_cache:
          keys:
            - v10-pip-cache-{{ checksum "setup.py" }}

      - run:
          name: Install EVA package with test dependencies
          command: |
            python -m venv eva_dev_env
            . eva_dev_env/bin/activate
            pip install --upgrade pip
            sh script/antlr4/generate_parser.sh
            pip install ".[dev]"

      - run:
          name: Test and upload coverage report to coveralls
          command: |
            sudo apt-get update          
            sudo apt-get install lsof 
            . eva_dev_env/bin/activate
            sh script/test/test.sh
            coveralls

      - save_cache:
          key: v10-model_cache-{{ checksum "setup.py" }}
          paths:
            - /home/circleci/.cache/torch/hub/
            - /home/circleci/.EasyOCR/

      - save_cache:
          key: v10-pip-cache-{{ checksum "setup.py" }}
          paths:
            - ./eva_dev_env/
