version: 2.1
jobs:
  test-linux:
    docker:
      - image: circleci/python:3.7
      - image: circleci/python:3.8
      - image: circleci/python:3.9
    working_directory: ~/project
    steps:
      - checkout
      - run: |
          python --version
          pip --version
          pip install -r requirements.txt
          pytest
  test-macos:
    macos:
      xcode: "12.4.0"
    environment:
      PYENV_ROOT: /usr/local/pyenv
      PATH: $PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH
    steps:
      - checkout
      - run: |
          brew update
          brew install pyenv
          eval "$(pyenv init -)"
          pyenv install $(pyenv install --list | grep "^\s*3\.[7-9]\.\d+$" | tail -1)
          pyenv global $(pyenv versions --bare | grep "^\s*3\.[7-9]\.\d+$" | sort -r | tr '\n' ' ')
          python --version
          pip --version
          pip install -r requirements.txt
          pytest
  test-windows:
    windows: latest
    environment:
      PATH: "C:\\Python{version}\\;C:\\Python{version}\\Scripts;C:\\Program Files\\Git\\bin\\;C:\\Program Files\\Git\\usr\\bin\\;C:\\Windows\\System32\\;C:\\Windows;C:\\Windows\\System32\\wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;$env:APPDATA\\Python\\Scripts;$env:APPDATA\\npm"
    steps:
      - checkout
      - run: |
          choco install python --version=$(choco search python --exact --limit-output --by-id-only --order-by-version-desc | grep "^python\s*\d\.\d" | awk '{print $2}' | head -n 1) --params "/InstallDir:C:\Python37" -y
          choco install python --version=$(choco search python --exact --limit-output --by-id-only --order-by-version-desc | grep "^python\s*\d\.\d" | awk '{print $2}' | head -n 1) --params "/InstallDir:C:\Python38" -y
          choco install python --version=$(choco search python --exact --limit-output --by-id-only --order-by-version-desc | grep "^python\s*\d\.\d" | awk '{print $2}' | head -n 1) --params "/InstallDir:C:\Python39" -y
          python --version
          pip --version
          pip install -r requirements.txt
          pytest
